export enum Configuracion {
    SUCURSAL = "SUC",
    IVA = "IVA",
    MONEDA = "MON",
    ESQUEMA_FIRMA = "ESFIR",
    TIPOS_DE_AUXILIAR_PARA_APIS = "TAAPI",
    DEPARTAMENTO_PARA_APIS = "DAPI",
    NOTIFICAR_CORREO = "NOTIF",
    CONFIR_PREVIA = "CNFIR",
    PERMITIR_DETALLE_REPETIDO_OC="VALOC",
    AUTOGENERAR_CODIGOS_ITEMS = "ACI",
    AUTOGENERAR_CODIGOS_AUXILIARCONTABLE = "AAX",
    PORCENTAJE_MAXIMO_ANTICIPO_OC ="PMAOC",
    MOSTRAR_TODOS_LOS_MOVIMIENTOS = "MTV",
    LISTA_PRECIO_CATEGORIA_COMPRA_POR_DEFECTO = "LPCAT",
    DIAS_ACTUALIZACION_LISTA_PRECIOS = "DALP",
    // Tolerancia en USD para diferencia entre total OC y total documento de regularización
    TOLERANCIA_TOTAL_REGULARIZACION_OC = "TTROC",
    ISD = "ISD",
    FORMA_PAGO_COMPROBANTE_DEFAULT = "CODFP",
    ROL_NOTIFICACION_PROVEEDURIA = "RNP"
  }