export enum NotificationHubMethods {
  mainNotificacionPushHub = "mainNotificacionPushHub",
  loadNotificacionPushHub = "loadNotificacionPushHub",
  paisNotification = "paisNotification",
  regionNotification = "regionNotification",
  requisicionNotification = "requisicionNotification",
  ordenCompraNotification = "ordenCompraNotification",
  buzonCorreoNotification = "buzonCorreoNotification",
  procesoDescargaLog = "procesoDescargaLog",
  recepcionCompraNotification = "recepcionCompraNotification",
  loteRecepcionCompraNotification = "loteRecepcionCompraNotification",
  loteRecepcionCompraUpdateNotification = "loteRecepcionCompraUpdateNotification",
  loteOrdenPagoNotification = "loteOrdenPagoNotification",
  solicitudAnticipoNotification = "solicitudAnticipoNotification",
  pagoElectronicoNotification = "pagoElectronicoNotification",
  listaPrecioNotification = "listaPrecioNotification",
  solicitudAprobacionListaPrecio = "solicitudAprobacionListaPrecio",
  chatTransaccionNotification = "chatTransaccionNotification",
  reposicionCajaNotification = "reposicionCajaNotification",
  receiveMessage = "receiveMessage",
  requerimientoInventarioNotification = "requerimientoInventarioNotification",
}