export enum Operacion {
    Crear = "N",
    Leer = "L",
    Modificar = "M",
    Eliminar = "E",
    Anular = "X",
    Aprobar = "A",
    Reversar = "R",
    ReversarAprobado = "RA",
    SolicitarAprobacion = "S",
    Imprimir ="I",
    Cerrar="C",
    Negar ="G",
    SetPassword ="SP",
    AgregarArchivo="AA",
    EliminarArchivo="EA",
    VerArchivo="VA",
    DescargarArchivo="DA",
    ModificarArchivo="MA",
    Auditoria="AD",
    VerPrecio="VP",
    HistorialPrecio="HPRE",
    Busqueda="B",
    Calificar="CA",
    Migrar="MG"
  }